### ISSUE TITLE
USER STORY: Get User Details

### ISSUE THREAD

**Issue by Kamal-Kohli** [Kamal-Kohli/ShareYourTaste#1]
Users must register to access the website when they visit the page.

# Acceptance Criteria:

- Acceptance Criteria 1: Pop-up SignIn/SignUp form
- Acceptance Criteria 2: Notify users if they have already signed

# Tasks:

- [ ] Provide e.g. how to fill out the signup form
- [ ] Warning alert while wrong input
- [ ] Add Submit and Cancel button
