### ISSUE TITLE
USER STORY: Provide Tour Package

### ISSUE THREAD

**Issue by Kamal-Kohli** [Kamal-Kohli/ShareYourTaste#2]
As a user, there are I can lots of Hot travel destinations

# Acceptance Criteria:

- Acceptance Criteria 1: Several Travel tour packages on the home page
- Acceptance Criteria 2: Notify users if they have already signed

# Tasks:

- [ ] Add travel package details with Thumbnails 
- [ ] Add read more options for more details regarding tour package
- [ ] Add "Booking button" to the package
